modLoader="javafml"
loaderVersion="[28,)"
updateJSONURL="https://raw.githubusercontent.com/MinecraftModDevelopmentMods/minecraftmineralogy/master/update.json"
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/minecraftmineralogy/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraftmineralogy"
logoFile=""
credits="SkyBlade1978"
authors="SkyBlade1978"

[[mods]]
modId="mineralogy"
version="${file.jarVersion}"
displayName="Minecraft Mineralogy"
description='''
Because there''s no such thing as ''stone''!
'''

[[dependencies.mineralogy]]
   modId="forge"
   mandatory=true
   versionRange="[28,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.mineralogy]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.4]"
   ordering="NONE"
   side="BOTH"